# Generated by Django 4.0.5 on 2022-10-11 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie_obj',
            fields=[
                ('categorie_objet', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerable_categorie',
            fields=[
                ('categorie_vulnerable', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerable_cible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible_vulnerable', models.CharField(default='null', max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('categorie_vulnerable', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='affecte.vulnerable_categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Type_obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_objet', models.CharField(default='null', max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('categorie_objet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='affecte.categorie_obj')),
            ],
        ),
    ]
