# Generated by Django 4.0.5 on 2022-09-16 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateuruser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 20, 34, 32, 350667, tzinfo=utc), verbose_name='last_login'),
        ),
        migrations.AlterField(
            model_name='donateuruser',
            name='numero',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='donateuruser',
            name='numero1',
            field=models.CharField(max_length=30),
        ),
    ]
