# Generated by Django 4.0.5 on 2022-10-11 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_effectuerdonarge_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateuruser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 10, 11, 59, 114805, tzinfo=utc), verbose_name='last_login'),
        ),
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='amount',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='currency',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='description',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='matadata',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='operator_id',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='payement_date',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='payement_method',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonarge',
            name='status',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
